from enum import Enum


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class RiskType(str, Enum):
    MISSING_CLAUSE = "MISSING_CLAUSE"
    NON_COMPETE = "NON_COMPETE"
    UNLIMITED_LIABILITY = "UNLIMITED_LIABILITY"
    TERMINATION_BIAS = "TERMINATION_BIAS"
    PAYMENT_AMBIGUITY = "PAYMENT_AMBIGUITY"
